# Generated by Django 4.0.5 on 2024-04-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('directors', models.CharField(max_length=255)),
                ('runtime', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
    ]
